### ISSUE TITLE
use naming to indicate the timestamp should be in second and not in millisecond

### ISSUE THREAD

**Issue by deneuxa** [toothrot/amplitude-api#10]
Perhaps change the naming of the time parameter to indicate the timestamp will be automatically converted in millisecond.

(I was converting in milliseconds myself before !, so the x1000 multiplication was done twice...)

something like occured_at ?

**Comment by toothrot** [comment]
Hey @deneuxa,

I chose "time" to mirror what Amplitude calls the event attribute, so that it matches. I'll update the gem documentation to make it more clear that it expects a Time object, and maybe a little defensive code around not multiplying something if it's an integer.

**Comment by deneuxa** [comment]
Hum not multiplying if it's an integer could be dangerous 
I'm using the gem with ActiveJob (so if amplitude API is down the job will fail and then try again, without blocking the app), but for now ActiveJob doesn't accept DateTime attributes, so I send an integer timestamp. (in seconds : default ruby timestamp result of .to_i )

Maybe with a setting ?

**Comment by AlvaroMaceda** [comment]
There is an option to change this behaviour, `AmplitudeAPI.config.time_formatter`. I've updated the documentation with that.
