### ISSUE TITLE
Example of using amplitude-api with Delayed Job

### ISSUE THREAD

**Issue by bvlaar** [toothrot/amplitude-api#18]
I've setup `amplitude-api` within my application and it is currently sending events synchronously. I'd like to move these to a background job in order to free up resources.

Can someone give me an example of how they did this? 

I currently have a method in my `amplitude.rb` module that looks like the following:

```
def track(event)
  AmplitudeAPI.delay.track(event)
end
```

For some reason the job is added to the `delayed_jobs` table but the logs just show the job as RUNNING and never COMPLETED.

It'd be helpful to see another example of how people are moving event submission to the background.

**Comment by AlvaroMaceda** [comment]
Hi, bvlaar. I'm closing this issue because it has been a lot of time since it's creation and I think it won't be relevant by now. If you continue experiencing problems with this, please open a new issue.
