### ISSUE TITLE
Please release 0.0.10

### ISSUE THREAD

**Issue by avokhmin** [toothrot/amplitude-api#25]

**Comment by avokhmin** [comment]
@toothrot , when I can expect next release of gem?

**Comment by avokhmin** [comment]
@toothrot , I did PR: https://github.com/toothrot/amplitude-api/pull/27 . Can you merge and create new release of gem?

**Comment by toothrot** [comment]
Yikes! Sorry! Done

**Comment by avokhmin** [comment]
@toothrot thanks!
