### ISSUE TITLE
RestClient::BadGateway 502

### ISSUE THREAD

**Issue by joker-777** [toothrot/amplitude-api#28]
Hello,

we are getting frequently this error when using your library. Could you please give us a hint why this could happen?

Thanks,

Johannes

**Comment by toothrot** [comment]
Hello!

Sorry for the delay. A 502 usually is caused by issues in the site you are trying to connect to. I would start by checking the status page of Amplitude when this happened.

It could also be caused by a bad proxy on your end, if your outgoing requests go through any kind of proxy.

**Comment by joker-777** [comment]
Hello, thanks for your response. It looks like this error only occurred between 28.2.2019 and 1.3.2019. It isn't an issue anymore
