### ISSUE TITLE
The amplitude initialization syntax is now broken on master

### ISSUE THREAD

**Issue by samjohn** [toothrot/amplitude-api#32]
I believe this commit broke it:  77c19889d1a78a88267ba381cf6030a634bb73a1
The instructions on the README no longer work: 
```
# Configure your Amplitude API key
AmplitudeAPI.api_key = "abcdef123456"
```
Will throw: 
```
NoMethodError: undefined method `api_key=' for AmplitudeAPI:Class
```

Before actually releasing 0.10 you should add back in that initialization option or change the doc to reflect the preferred initialization route. 

Switching to: 
```
AmplitudeAPI.config.api_key = "abcdef123456"
```
will properly initialize the gem.

**Comment by samjohn** [comment]
@kolorahl ^ Do you have a preference?

**Comment by kolorahl** [comment]
Sorry about the late reply.

Yeah, definitely did not have a preference there.
