### ISSUE TITLE
Unable to see events

### ISSUE THREAD

**Issue by gerbil802** [toothrot/amplitude-api#35]
Hi,

I've set this up, and it appears `AmplitudeAPI.config.api_key = ...` doesn't exist, but this works: `AmplitudeAPI.api_key = ...`. 
But now I send events but I can't see them on the dashboard. Any idea?

**Comment by kolorahl** [comment]
The latest version of `master` should use the `AmplitudeAPI.config.api_key` syntax (as pointed out in issue #32). Are you using the latest version from RubyGems or are you grabbing the latest changes from `master`?

**Comment by gerbil802** [comment]
Using RubyGems - `amplitude-api (0.0.10)`.. Should I point it to `master` branch instead?

**Comment by kolorahl** [comment]
There are a lot of change on `master` that make working with Amplitude simpler and also provide integration with the new deletion functionality as per GDPR (see #34). Ideally we should be bumping the version soon but if you are having problems with `0.0.10` I would try using `master` instead.

**Comment by gerbil802** [comment]
OK That solved it. I have another issue though now, will open another ticket.
