### ISSUE TITLE
User deletion syntax is a bit different from the on in readme

### ISSUE THREAD

**Issue by smostovoy** [toothrot/amplitude-api#41]
`AmplitudeAPI.delete(user_ids: [233], ...)` doesn't work. I didn't dig much but  passing a single value works fine - `AmplitudeAPI.delete(user_ids: 233, ...)`.  Not sure what should be fixed - readme or the method. Probably the method

**Comment by toothrot** [comment]
This method was contributed to this gem by someone else, so I am not immediately familiar.

Looking at the documentation for this API call, it seems like it is supposed to accept an array of strings: https://developers.amplitude.com/#User-Privacy-API-List-deletion-jobs

```json
  "user_ids": [
    "user_id_1",
    "user_id_2",
    "..."
  ],
```

I'll do some testing and see what is happening.

**Comment by toothrot** [comment]
Hey @smostovoy, I was able to reproduce this and am currently working on a fix.
