### ISSUE TITLE
deprecated http v1 api

### ISSUE THREAD

**Issue by MehdiSv** [toothrot/amplitude-api#49]
Hi,

Amplitude just deprecated the v1 of their api.

The gem needs to be updated to handle the http v2 of their API.

https://help.amplitude.com/hc/en-us/articles/204771828-HTTP-API-Deprecated-

**Comment by danielventulieri** [comment]
Has there been any progress on this? Looks like the repo hasn't been maintained for a few months now.

**Comment by AlvaroMaceda** [comment]
The code has been upgraded to the new API in version 0.2.0. It's not in rubygems yet, but you can use the code from the repository.
