### ISSUE TITLE
 Could not open library 'libcurl': libcurl: cannot open shared object file: No such file or directory. (LoadError)

### ISSUE THREAD

**Issue by vikramdmrsool** [toothrot/amplitude-api#51]
OS: Ubuntu 16.04.6 LTS

```
Could not open library 'libcurl.so': libcurl.so: cannot open shared object file: No such file or directory.
Could not open library 'libcurl.so.4': libcurl.so.4: cannot open shared object file: No such file or directory
	...
/home/ubuntu/.rvm/gems/ruby-2.6.5/gems/ffi-1.9.18/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library 'libcurl': libcurl: cannot open shared object file: No such file or directory. (LoadError)

```

**Comment by obahareth** [comment]
Also seeing this on AWS Elastic Beanstalk.

**Comment by AlvaroMaceda** [comment]
Typhoeus requires libcurl-4. It seems it's not installed in your system. Could you please check it you can solve it with [this information](https://rubydoc.info/gems/typhoeus/0.4.2/frames)?

**Comment by AlvaroMaceda** [comment]
Version 0.3.0 of the gem uses Faraday instead of Typhoeus, so you shouldn't have this problem anymore. Please, open a new issue in case you keep experiencing problems.
