### ISSUE TITLE
Rubygems release

### ISSUE THREAD

**Issue by sabrinathecodewitch** [toothrot/amplitude-api#56]
Thanks for this gem! It's been super helpful, and I'm looking to pull in the changes that were requested in https://github.com/toothrot/amplitude-api/issues/54 and just need a bit of clarification:

We're currently pulling in the gem from Rubygems, but it looks like [it hasn't been released there for a while](https://rubygems.org/gems/amplitude-api) (latest version is 0.1.1 there, looks like that's also what's listed in the readme badge). 

I'm wondering if there will be a new release to Rubygems?

Thanks for your time!

**Comment by toothrot** [comment]
I've made @AlvaroMaceda an owner, as they've been doing all the maintenance! I think a new release is immanent.

**Comment by AlvaroMaceda** [comment]
I've published it a moment ago. Please, let me know if everything works fine for you.

**Comment by sabrinathecodewitch** [comment]
Looks like I have some gem dependencies to sort out, but thank you for this update!
I'll follow up if there are any issues, appreciate the fast turnaround time on this 🙂
