### ISSUE TITLE
Support `event.time`

### ISSUE THREAD

**Issue by micho** [toothrot/amplitude-api#8]
Hi! Thanks for the great gem :)

Are you planning to add support for `event.time`, so one can send events in the past with specific timestamps?

https://amplitude.zendesk.com/hc/en-us/articles/204771828-HTTP-API

**Comment by toothrot** [comment]
Hey @micho!

Sure! I just didn't need it at the time of writing this. I'll try to add it soon.

**Comment by toothrot** [comment]
@micho released! https://github.com/toothrot/amplitude-api/releases/tag/v0.0.5

Tested it against my dev account, and it works.

**Comment by micho** [comment]
Beautiful! :sparkles: Thanks for the speedy addition, I'll incorporate it to our project today :)
